// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheBatCoreWebScrapper.DAL;

namespace TheBatCoreWebScrapper.DAL.Migrations
{
    [DbContext(typeof(ScrapperContext))]
    [Migration("20200410150826_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheBatCoreWebScrapper.DAL.Models.ScrappingResult", b =>
                {
                    b.Property<int>("ScrappingResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BodyResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UrlLibraryId")
                        .HasColumnType("int");

                    b.HasKey("ScrappingResultId");

                    b.HasIndex("UrlLibraryId");

                    b.ToTable("ScrappingResults");
                });

            modelBuilder.Entity("TheBatCoreWebScrapper.DAL.Models.UrlLibrary", b =>
                {
                    b.Property<int>("UrlLibraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrlLibraryId");

                    b.ToTable("UrlLibraries");
                });

            modelBuilder.Entity("TheBatCoreWebScrapper.DAL.Models.ScrappingResult", b =>
                {
                    b.HasOne("TheBatCoreWebScrapper.DAL.Models.UrlLibrary", "UrlLibrary")
                        .WithMany()
                        .HasForeignKey("UrlLibraryId");
                });
#pragma warning restore 612, 618
        }
    }
}
